name: HeatDesign
favicon: null
layout_spectrum: 0.8967938972637057
typography_spectrum: 0.35086742136627436
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.4392948909662664
  lightness: 0.00155892432667315
  saturation: 0.004910471383482218
  rhythmicContrast: 0.7361369330901653
purpose: []
